name: Create Release

on:
  push:
    tags:
      - 'v*' # Run when tag matches v*, e.g., v1.0.0

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v

  create-release:
    needs: build-and-test
    runs-on: macos-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
    - uses: actions/checkout@v4
    
    - name: Create application bundle
      run: |
        chmod +x ./build.sh
        ./build.sh
    
    - name: Create ZIP archives
      run: |
        # Create app archive
        cd build
        zip -r ../Weatherspoon.zip Weatherspoon.app
        cd ..
        
        # Create source archive
        mkdir -p release
        cp -r Sources release/
        cp -r Resources release/
        cp Package.swift release/
        cp VERSION release/
        cp build.sh release/
        cp README.md release/
        cd release
        zip -r ../Weatherspoon-source.zip .
        cd ..
    
    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          Weatherspoon.zip
          Weatherspoon-source.zip
          VERSION
        body: |
          # Weatherspoon ${{ steps.get_version.outputs.VERSION }}
          
          A macOS menu bar app to display current weather information based on your location or a specified city.
          
          ## Installation
          
          1. Download the Weatherspoon.zip file
          2. Unzip the file
          3. Move Weatherspoon.app to your Applications folder
          4. Open the application